<?php

namespace Database\Seeders;

use App\Models\Animal;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Faker\Generator as Faker;

class AnimalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $animals = [
            [
                'nome_comune' => 'Leone',
                'nome_scientifico' => 'Panthera leo',
                'specie' => 'Mammifero',
                'data_di_nascita' => '2020-08-15',
                'peso' => 190.5,
                'altezza' => 1.2,
                'sesso' => 'maschio',
                'colore' => 'Marrone',
                'habitat' => 'Savana',
                'dieta' => 'Carnivoro',
                'stato_di_conservazione' => 'Vulnerabile',
                'provenienza' => 'Africa',
                'microchip_id' => 'ABC123456789',
            ],
            [
                'nome_comune' => 'Elefante Africano',
                'nome_scientifico' => 'Loxodonta africana',
                'specie' => 'Mammifero',
                'data_di_nascita' => '2018-04-22',
                'peso' => 6000.0,
                'altezza' => 3.3,
                'sesso' => 'femmina',
                'colore' => 'Grigio',
                'habitat' => 'Savana',
                'dieta' => 'Erbivoro',
                'stato_di_conservazione' => 'Vulnerabile',
                'provenienza' => 'Africa',
                'microchip_id' => 'DEF456789012',
            ],
            [
                'nome_comune' => 'Giraffa',
                'nome_scientifico' => 'Giraffa camelopardalis',
                'specie' => 'Mammifero',
                'data_di_nascita' => '2017-06-10',
                'peso' => 800.0,
                'altezza' => 5.5,
                'sesso' => 'maschio',
                'colore' => 'Giallo con macchie marroni',
                'habitat' => 'Savana',
                'dieta' => 'Erbivoro',
                'stato_di_conservazione' => 'Vulnerabile',
                'provenienza' => 'Africa',
                'microchip_id' => 'GHI789012345',
            ],
            [
                'nome_comune' => 'Tigre del Bengala',
                'nome_scientifico' => 'Panthera tigris tigris',
                'specie' => 'Mammifero',
                'data_di_nascita' => '2019-02-18',
                'peso' => 220.5,
                'altezza' => 1.1,
                'sesso' => 'femmina',
                'colore' => 'Arancione con strisce nere',
                'habitat' => 'Foresta',
                'dieta' => 'Carnivoro',
                'stato_di_conservazione' => 'In pericolo',
                'provenienza' => 'Asia',
                'microchip_id' => 'JKL012345678',
            ],
            [
                'nome_comune' => 'Pinguino Imperatore',
                'nome_scientifico' => 'Aptenodytes forsteri',
                'specie' => 'Uccello',
                'data_di_nascita' => '2016-12-25',
                'peso' => 30.0,
                'altezza' => 1.2,
                'sesso' => 'maschio',
                'colore' => 'Nero e bianco',
                'habitat' => 'Antartide',
                'dieta' => 'Carnivoro',
                'stato_di_conservazione' => 'Quasi minacciato',
                'provenienza' => 'Antartide',
                'microchip_id' => 'MNO345678901',
            ],
            [
                'nome_comune' => 'Koala',
                'nome_scientifico' => 'Phascolarctos cinereus',
                'specie' => 'Mammifero',
                'data_di_nascita' => '2021-01-15',
                'peso' => 9.0,
                'altezza' => 0.75,
                'sesso' => 'femmina',
                'colore' => 'Grigio',
                'habitat' => 'Foresta di eucalipti',
                'dieta' => 'Erbivoro',
                'stato_di_conservazione' => 'Vulnerabile',
                'provenienza' => 'Australia',
                'microchip_id' => 'PQR678901234',
            ],
            [
                'nome_comune' => 'Panda Gigante',
                'nome_scientifico' => 'Ailuropoda melanoleuca',
                'specie' => 'Mammifero',
                'data_di_nascita' => '2015-07-29',
                'peso' => 100.0,
                'altezza' => 1.5,
                'sesso' => 'maschio',
                'colore' => 'Bianco e nero',
                'habitat' => 'Foresta di bambù',
                'dieta' => 'Erbivoro',
                'stato_di_conservazione' => 'Vulnerabile',
                'provenienza' => 'Cina',
                'microchip_id' => 'STU901234567',
            ],
            [
                'nome_comune' => 'Canguro Rosso',
                'nome_scientifico' => 'Macropus rufus',
                'specie' => 'Mammifero',
                'data_di_nascita' => '2018-11-12',
                'peso' => 85.0,
                'altezza' => 1.8,
                'sesso' => 'femmina',
                'colore' => 'Rosso-marrone',
                'habitat' => 'Outback australiano',
                'dieta' => 'Erbivoro',
                'stato_di_conservazione' => 'Non minacciato',
                'provenienza' => 'Australia',
                'microchip_id' => 'VWX234567890',
            ],
            [
                'nome_comune' => 'Orso Polare',
                'nome_scientifico' => 'Ursus maritimus',
                'specie' => 'Mammifero',
                'data_di_nascita' => '2013-09-21',
                'peso' => 450.0,
                'altezza' => 2.4,
                'sesso' => 'maschio',
                'colore' => 'Bianco',
                'habitat' => 'Artico',
                'dieta' => 'Carnivoro',
                'stato_di_conservazione' => 'Vulnerabile',
                'provenienza' => 'Artico',
                'microchip_id' => 'YZA567890123',
            ],
            [
                'nome_comune' => 'Orangutan',
                'nome_scientifico' => 'Pongo pygmaeus',
                'specie' => 'Mammifero',
                'data_di_nascita' => '2011-05-30',
                'peso' => 75.0,
                'altezza' => 1.5,
                'sesso' => 'femmina',
                'colore' => 'Arancione',
                'habitat' => 'Foresta pluviale',
                'dieta' => 'Onnivoro',
                'stato_di_conservazione' => 'In pericolo critico',
                'provenienza' => 'Borneo',
                'microchip_id' => 'BCD890123456',
            ],
            [
                'nome_comune' => 'Rinoceronte Bianco',
                'nome_scientifico' => 'Ceratotherium simum',
                'specie' => 'Mammifero',
                'data_di_nascita' => '2010-02-14',
                'peso' => 2300.0,
                'altezza' => 1.8,
                'sesso' => 'maschio',
                'colore' => 'Grigio',
                'habitat' => 'Savana',
                'dieta' => 'Erbivoro',
                'stato_di_conservazione' => 'Quasi minacciato',
                'provenienza' => 'Africa',
                'microchip_id' => 'EFG123456789',
            ],
            [
                'nome_comune' => 'Coccodrillo del Nilo',
                'nome_scientifico' => 'Crocodylus niloticus',
                'specie' => 'Rettili',
                'data_di_nascita' => '2012-08-06',
                'peso' => 500.0,
                'altezza' => 4.2,
                'sesso' => 'femmina',
                'colore' => 'Verde scuro',
                'habitat' => 'Fiumi e laghi',
                'dieta' => 'Carnivoro',
                'stato_di_conservazione' => 'Non minacciato',
                'provenienza' => 'Africa',
                'microchip_id' => 'HIJ345678901',
            ],
            [
                'nome_comune' => 'Tartaruga Gigante delle Galápagos',
                'nome_scientifico' => 'Chelonoidis nigra',
                'specie' => 'Rettili',
                'data_di_nascita' => '1999-03-27',
                'peso' => 300.0,
                'altezza' => 1.0,
                'sesso' => 'maschio',
                'colore' => 'Verde',
                'habitat' => 'Isole Galápagos',
                'dieta' => 'Erbivoro',
                'stato_di_conservazione' => 'Vulnerabile',
                'provenienza' => 'Galápagos',
                'microchip_id' => 'KLM456789012',
            ],
            [
                'nome_comune' => 'Ippopotamo',
                'nome_scientifico' => 'Hippopotamus amphibius',
                'specie' => 'Mammifero',
                'data_di_nascita' => '2014-11-19',
                'peso' => 1500.0,
                'altezza' => 1.5,
                'sesso' => 'femmina',
                'colore' => 'Grigio',
                'habitat' => 'Fiumi e laghi',
                'dieta' => 'Erbivoro',
                'stato_di_conservazione' => 'Vulnerabile',
                'provenienza' => 'Africa',
                'microchip_id' => 'NOP678901234',
            ],
            [
                'nome_comune' => 'Scimpanzé',
                'nome_scientifico' => 'Pan troglodytes',
                'specie' => 'Mammifero',
                'data_di_nascita' => '2010-07-08',
                'peso' => 60.0,
                'altezza' => 1.2,
                'sesso' => 'maschio',
                'colore' => 'Nero',
                'habitat' => 'Foresta',
                'dieta' => 'Onnivoro',
                'stato_di_conservazione' => 'In pericolo',
                'provenienza' => 'Africa',
                'microchip_id' => 'QRS789012345',
            ],
            [
                'nome_comune' => 'Fenicottero Rosa',
                'nome_scientifico' => 'Phoenicopterus roseus',
                'specie' => 'Uccello',
                'data_di_nascita' => '2016-04-16',
                'peso' => 2.5,
                'altezza' => 1.2,
                'sesso' => 'femmina',
                'colore' => 'Rosa',
                'habitat' => 'Zone umide',
                'dieta' => 'Onnivoro',
                'stato_di_conservazione' => 'Non minacciato',
                'provenienza' => 'Africa',
                'microchip_id' => 'TUV890123456',
            ],
            [
                'nome_comune' => 'Cobra Reale',
                'nome_scientifico' => 'Ophiophagus hannah',
                'specie' => 'Rettili',
                'data_di_nascita' => '2017-12-03',
                'peso' => 5.0,
                'altezza' => 3.5,
                'sesso' => 'maschio',
                'colore' => 'Verde oliva',
                'habitat' => 'Foresta',
                'dieta' => 'Carnivoro',
                'stato_di_conservazione' => 'Vulnerabile',
                'provenienza' => 'Asia',
                'microchip_id' => 'WXY901234567',
            ],
            [
                'nome_comune' => 'Lemure Catta',
                'nome_scientifico' => 'Lemur catta',
                'specie' => 'Mammifero',
                'data_di_nascita' => '2013-06-14',
                'peso' => 2.2,
                'altezza' => 0.4,
                'sesso' => 'femmina',
                'colore' => 'Grigio con coda ad anelli',
                'habitat' => 'Foresta tropicale',
                'dieta' => 'Onnivoro',
                'stato_di_conservazione' => 'Quasi minacciato',
                'provenienza' => 'Madagascar',
                'microchip_id' => 'XYZ234567890',
            ],
            [
                'nome_comune' => 'Orso Bruno',
                'nome_scientifico' => 'Ursus arctos',
                'specie' => 'Mammifero',
                'data_di_nascita' => '2009-09-09',
                'peso' => 350.0,
                'altezza' => 2.2,
                'sesso' => 'maschio',
                'colore' => 'Marrone',
                'habitat' => 'Foresta e montagna',
                'dieta' => 'Onnivoro',
                'stato_di_conservazione' => 'Non minacciato',
                'provenienza' => 'Europa',
                'microchip_id' => 'ABC345678901',
            ],
            [
                'nome_comune' => 'Lupo Grigio',
                'nome_scientifico' => 'Canis lupus',
                'specie' => 'Mammifero',
                'data_di_nascita' => '2012-03-23',
                'peso' => 45.0,
                'altezza' => 0.85,
                'sesso' => 'femmina',
                'colore' => 'Grigio',
                'habitat' => 'Foresta e tundra',
                'dieta' => 'Carnivoro',
                'stato_di_conservazione' => 'Non minacciato',
                'provenienza' => 'Nord America',
                'microchip_id' => 'DEF456789712',
            ],
            [
                'nome_comune' => 'Iguana Verde',
                'nome_scientifico' => 'Iguana iguana',
                'specie' => 'Rettili',
                'data_di_nascita' => '2018-10-11',
                'peso' => 4.5,
                'altezza' => 1.5,
                'sesso' => 'maschio',
                'colore' => 'Verde',
                'habitat' => 'Foresta tropicale',
                'dieta' => 'Erbivoro',
                'stato_di_conservazione' => 'Non minacciato',
                'provenienza' => 'Sud America',
                'microchip_id' => 'GHI789012945',
            ],
        ];

        foreach ($animals as $animal ) {

            $newAnimal= new Animal();
            $newAnimal->nome_comune = $animal['nome_comune'];
            $newAnimal->nome_scientifico = $animal['nome_scientifico'];
            $newAnimal->specie = $animal['specie'];
            $newAnimal->data_di_nascita = $animal['data_di_nascita'];
            $newAnimal->peso = $animal['peso'];
            $newAnimal->altezza = $animal['altezza'];
            $newAnimal->sesso = $animal['sesso'];
            $newAnimal->colore = $animal['colore'];
            $newAnimal->habitat = $animal['habitat'];
            $newAnimal->dieta = $animal['dieta'];
            $newAnimal->stato_di_conservazione = $animal['stato_di_conservazione'];
            $newAnimal->provenienza = $animal['provenienza'];
            $newAnimal->microchip_id = $animal['microchip_id'];
            $newAnimal->save();

        };
    }
}
